const ENV = {
  data: [
    {
      key: '1',
      goods: 'book',
      price: 12.49,
      quantity: 0,
      check: false,
      rate: 0,
    }, {
      key: '2',
      goods: 'music CD',
      price: 14.99,
      quantity: 0,
      check: false,
      rate: 0.1,
    }, {
      key: '3',
      goods: 'chocolate bar',
      price: 0.85,
      quantity: 0,
      check: false,
      rate: 0,
    }, {
      key: '4',
      goods: 'imported box of chocolates',
      price: 10.00,
      quantity: 0,
      check: false,
      rate: 0.05,
    }, {
      key: '5',
      goods: 'imported bottle of perfume',
      price: 47.50,
      quantity: 0,
      check: false,
      rate: 0.15,
    }, {
      key: '6',
      goods: 'bottle of perfume',
      price: 18.99,
      quantity: 0,
      check: false,
      rate: 0.1,
    }, {
      key: '7',
      goods: 'packet of headache pills',
      price: 9.75,
      quantity: 0,
      check: false,
      rate: 0,
    }, {
      key: '8',
      goods: 'imported watch',
      price: 27.99,
      quantity: 0,
      check: false,
      rate: 0.15,
    }, {
      key: '9',
      goods: 'box of imported cake',
      price: 11.25,
      quantity: 0,
      check: false,
      rate: 0.05,
    }],
};
